logging:
  level:
    web: debug
spring:
  application:
    name: BaldursGateThreeAPI
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: myuser #{DATABASE_USERNAME}
    password: secret #{DATABASE_PASSWORD}